---
title: react错误处理
date: 2023-04-13T02:28:49.374Z
size: 2810
---
React 16 开始，未被任何ErrorBoundary捕获的错误将导致整个React 组件树的卸载(页面空白)
##### 常规处理方式
```jsx
const SomeComponent = () => {  
  const [hasError, setHasError] = useState(false);  
  
  useEffect(() => {  
    try {
	    ...  
    } catch(e) {  
      setHasError(true);  
    }  
  }, [])  
  
  if (hasError) return <SomeErrorScreen />  
  
  return <SomeComponentContent {...datasomething} />  
}
```

##### ErrorBoundary
- 非原生组件，只提供了实现方式
- try/catch只能捕获其语句块内部发生的错误
- ErrorBoundary可以捕获发生在React生命周期中的错误
	- 异步代码、各种回调和事件监听函数，如果没有被明确处理，将不能捕获
- 支持fallback UI ,当错误发生的时候展示给用户
- 可以从错误中恢复,并继续渲染其他子组件树，避免整个应用crashed

```jsx
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(error) {
    // Update state so the next render will show the fallback UI.
    return { hasError: true };
  }

  componentDidCatch(error, errorInfo) {
    // You can also log the error to an error reporting service
    logErrorToMyService(error, errorInfo);
  }

  render() {
    if (this.state.hasError) {
      // You can render any custom fallback UI
      return <h1>Something went wrong.</h1>;
    }

    return this.props.children; 
  }
}
```
###### ErrorBoundary捕捉异步错误
- try/catch捕获错误
- 通过state变化触发重新渲染
```jsx
const Component = () => {  
  const [state, setState] = useState();  
  
  const onClick = () => {  
    try {  
      // something bad happened  
    } catch (e) {  
      setState(() => {  
        throw e;  
      })  
    }  
  }  
}

// hooks
const useThrowAsyncError = () => {
    const [state, setState] = useState()

    return (error) => {
        setState(() => {
            throw error
        })
    }
}
```
##### react-error-boundary
```jsx
"use client";

import { ErrorBoundary } from "react-error-boundary";

// 错误提示
const ErrorFallback = ({ error, resetErrorBoundary }) => {
  return (
    <div role="alert">
      <p>Something went wrong:</p>
      <pre style={{ color: "red" }}>{error.message}</pre>
    </div>
  );
}

// 错误日志上报
const logError = (error: Error, info: { componentStack: string }) => {};

<ErrorBoundary
  FallbackComponent={ErrorFallback} 
  onError={logError}
>
  <ExampleApplication />
</ErrorBoundary>;
```

refs:
- https://github.com/bvaughn/react-error-boundary
- https://github.com/facebook/react/issues/14981
